# Generated by Django 6.0.7 on 2026-08-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='mcq/questions/audio/'),
        ),
    ]
