# Generated by Django 6.0.8 on 2026-08-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_option_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='mcq/options/audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown after answering.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mcq/questions/images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Question text / prompt.'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='category',
            field=models.CharField(choices=[('Language_practice', 'Language Practice'), ('aptitude', 'Aptitude'), ('visa_interview_prep', 'Visa Interview Prep'), ('general_knowledge', 'General Knowledge'), ('others', 'Others')], default='others', max_length=32),
        ),
    ]
