# Generated by Django 6.0.8 on 2026-08-27 10:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_option_audio_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='mcq/options/audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='mcq/questions/audio/'),
        ),
    ]
