# Generated by Django 6.0.5 on 2026-09-10 02:20

import mcq.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_alter_option_audio_alter_question_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=mcq.storage.CloudinaryAudioStorage(), upload_to='mcq/options/audio/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=mcq.storage.CloudinaryMediaStorage(), upload_to='mcq/options/images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=mcq.storage.CloudinaryAudioStorage(), upload_to='mcq/questions/audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=mcq.storage.CloudinaryMediaStorage(), upload_to='mcq/questions/images/'),
        ),
    ]
