# Generated by Django 6.0.7 on 2026-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mcq_access',
            field=models.BooleanField(default=False, help_text='Whether the student can access the MCQ module.'),
        ),
    ]
