# Generated by Django 6.0.7 on 2026-08-08 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_mcq_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-passout_year', '-end_date']},
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric GPA/percentage value', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa_scale',
            field=models.CharField(blank=True, choices=[('4.0', 'Out of 4.0'), ('100', 'Percentage')], help_text='What scale the `gpa` value is on, e.g. out of 4.0 or a percentage', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='passout_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year this qualification was/will be completed', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_study_level',
            field=models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD')], max_length=32),
        ),
    ]