# Generated by Django 6.0.8 on 2026-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_education_options_education_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='book_access',
            field=models.BooleanField(default=False, help_text='Whether the student can access the Books module.'),
        ),
    ]
