# Generated by Django 6.0.5 on 2026-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_book_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current application step for the student.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PHD')], max_length=32),
        ),
    ]
