# Generated by Django 6.0.5 on 2026-09-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, max_length=50)),
                ('interview_result', models.CharField(blank=True, max_length=100)),
                ('interview_notes', models.TextField(blank=True)),
                ('application_ref_no', models.CharField(blank=True, max_length=100)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('confirmation_file_name', models.CharField(blank=True, max_length=255)),
                ('offer_file_name', models.CharField(blank=True, max_length=255)),
                ('offer_type', models.CharField(blank=True, max_length=100)),
                ('offer_expiry_date', models.DateField(blank=True, null=True)),
                ('loc_file_name', models.CharField(blank=True, max_length=255)),
                ('loc_verified', models.BooleanField(default=False)),
                ('course_commencement_date', models.DateField(blank=True, null=True)),
                ('scholarship_status', models.CharField(blank=True, max_length=100)),
                ('final_selection_notes', models.TextField(blank=True)),
                ('final_selection_confirmed', models.BooleanField(default=False)),
                ('visa_ref_no', models.CharField(blank=True, max_length=100)),
                ('visa_status_update', models.CharField(blank=True, max_length=100)),
                ('visa_approval_letter_file_name', models.CharField(blank=True, max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=100)),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('departure_airport', models.CharField(blank=True, max_length=150)),
                ('arrival_airport', models.CharField(blank=True, max_length=150)),
                ('departure_date_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='students.studentprofile')),
            ],
        ),
    ]
