# Generated by Django 6.0.5

import storage.supabase_student_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_studentapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentapplication",
            name="confirmation_file_name",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="loc_file_name",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="offer_file_name",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="ticket_file_name",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="visa_approval_letter_file_name",
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="confirmation_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage.supabase_student_storage.SupabaseStudentStorage(),
                upload_to="applications/step5/",
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="loc_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage.supabase_student_storage.SupabaseStudentStorage(),
                upload_to="applications/step7/",
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="offer_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage.supabase_student_storage.SupabaseStudentStorage(),
                upload_to="applications/step6/",
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="ticket_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage.supabase_student_storage.SupabaseStudentStorage(),
                upload_to="applications/step10/",
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="visa_approval_letter_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storage.supabase_student_storage.SupabaseStudentStorage(),
                upload_to="applications/step9/",
            ),
        ),
    ]