# Generated by Django 6.0.5 on 2026-09-10 11:42

import storage.supabase_student_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_studentapplication_confirmation_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='step1_photo',
            field=models.FileField(blank=True, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step1/'),
        ),
    ]
