# Generated by Django 6.0.5 on 2026-09-10 15:51

import storage.supabase_student_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentapplication_step1_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='confirmation_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step5/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='loc_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step7/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='offer_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step6/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='step1_photo',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step1/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ticket_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step10/'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='visa_approval_letter_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/step9/'),
        ),
    ]
