# Generated by Django 6.0.5 on 2026-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentapplication_confirmation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='transcript_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='applications/transcript/'),
        ),
    ]
