# Generated by Django 6.0.5 on 2026-09-13 05:02

import storage.supabase_student_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentapplication_transcript_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='transcript_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=storage.supabase_student_storage.SupabaseStudentStorage(), upload_to='applications/transcript/'),
        ),
    ]
