# Generated by Django 6.0.5 on 2026-09-10 02:20

import books.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(storage=books.storage.SupabaseBookStorage(), upload_to='books/pdfs/'),
        ),
    ]
