# Generated by Django 6.0.7 on 2026-07-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('countries', '0001_initial'),
        ('documents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('submitted', 'Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='preparing', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_applications', to='applications.application')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='countries.country')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_links', to='documents.document')),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_documents', to='visas.visaapplication')),
            ],
            options={
                'unique_together': {('visa_application', 'document')},
            },
        ),
    ]
