# Generated by Django 6.0.5 on 2026-09-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_create_missing_student_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprocess',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprocess',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='process.processstage'),
        ),
    ]
