# Generated by Django 6.0.7 on 2026-07-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('pte', 'PTE'), ('duolingo', 'Duolingo English Test'), ('other', 'Other')], max_length=16)),
                ('test_date', models.DateField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_breakdown', models.JSONField(blank=True, help_text='e.g. listening/reading/writing/speaking', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_test_certificates', to='documents.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_tests', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
