# Generated by Django 6.0.7 on 2026-08-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('bhojpur', 'Bhojpur'), ('dhankuta', 'Dhankuta'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('khotang', 'Khotang'), ('morang', 'Morang'), ('okhaldhunga', 'Okhaldhunga'), ('panchthar', 'Panchthar'), ('sankhuwasabha', 'Sankhuwasabha'), ('solukhumbu', 'Solukhumbu'), ('sunsari', 'Sunsari'), ('taplejung', 'Taplejung'), ('tehrathum', 'Tehrathum'), ('udayapur', 'Udayapur'), ('bara', 'Bara'), ('dhanusha', 'Dhanusha'), ('mahottari', 'Mahottari'), ('parsa', 'Parsa'), ('rautahat', 'Rautahat'), ('saptari', 'Saptari'), ('sarlahi', 'Sarlahi'), ('siraha', 'Siraha'), ('bhaktapur', 'Bhaktapur'), ('chitwan', 'Chitwan'), ('dhading', 'Dhading'), ('dolakha', 'Dolakha'), ('kathmandu', 'Kathmandu'), ('kavrepalanchok', 'Kavrepalanchok'), ('lalitpur', 'Lalitpur'), ('makwanpur', 'Makwanpur'), ('nuwakot', 'Nuwakot'), ('ramechhap', 'Ramechhap'), ('rasuwa', 'Rasuwa'), ('sindhuli', 'Sindhuli'), ('sindhupalchok', 'Sindhupalchok'), ('baglung', 'Baglung'), ('gorkha', 'Gorkha'), ('kaski', 'Kaski'), ('lamjung', 'Lamjung'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('nawalpur', 'Nawalpur (Nawalparasi East)'), ('parbat', 'Parbat'), ('syangja', 'Syangja'), ('tanahun', 'Tanahun'), ('arghakhanchi', 'Arghakhanchi'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('dang', 'Dang'), ('gulmi', 'Gulmi'), ('kapilvastu', 'Kapilvastu'), ('parasi', 'Parasi (Nawalparasi West)'), ('palpa', 'Palpa'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum_east', 'Rukum East'), ('rupandehi', 'Rupandehi'), ('dailekh', 'Dailekh'), ('dolpa', 'Dolpa'), ('humla', 'Humla'), ('jajarkot', 'Jajarkot'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('rukum_west', 'Rukum West'), ('salyan', 'Salyan'), ('surkhet', 'Surkhet'), ('achham', 'Achham'), ('baitadi', 'Baitadi'), ('bajhang', 'Bajhang'), ('bajura', 'Bajura'), ('dadeldhura', 'Dadeldhura'), ('darchula', 'Darchula'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi'), ('madhesh', 'Madhesh'), ('bagmati', 'Bagmati'), ('gandaki', 'Gandaki'), ('lumbini', 'Lumbini'), ('karnali', 'Karnali'), ('sudurpashchim', 'Sudurpashchim')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
