# Generated by Django 6.0.5 on 2026-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_district_user_province_user_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('ubt', 'UBT'), ('counselor', 'Counselor'), ('admin', 'Admin'), ('university_partner', 'University Partner')], default='student', max_length=32),
        ),
    ]
