# Generated by Django 6.0.7 on 2026-07-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, max_length=150)),
                ('flight_number', models.CharField(blank=True, max_length=50)),
                ('departure_airport', models.CharField(max_length=150)),
                ('arrival_airport', models.CharField(max_length=150)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('ticket_file', models.FileField(blank=True, null=True, upload_to='flight_tickets/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-departure_date'],
            },
        ),
    ]
